# filepath: /Users/pretz/Desktop/react-couse/fhan/word-card/.github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
      VITE_SHEET_ID: ${{ secrets.VITE_SHEET_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify env (values hidden)
        run: |
          if [ -z "$VITE_API_KEY" ] || [ -z "$VITE_SHEET_ID" ]; then
            echo "One or more VITE_* env vars are missing"; exit 1; fi
          echo "Env present"

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist